version: '3.8'

services:
  stt-tts-gateway:
    build: .
    ports:
      - "8089:8089"
    environment:
      - STT_MODEL_SIZE=base
      - TTS_MODEL_NAME=tts_models/en/ljspeech/tacotron2-DDC_ph
      - AUDIO_STORAGE_PATH=/app/audio
      - MAX_AUDIO_SIZE_MB=50
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8080
    volumes:
      - ./audio:/app/audio
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8089/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
