version: '3.8'

services:
  bytebot-gateway:
    build: .
    ports:
      - "8089:8089"
    environment:
      - LOG_LEVEL=INFO
      - SHARED_SECRET=test-secret-key-change-in-production
      - BYTEBOT_URL=http://host.docker.internal:3000
      - BYTEBOT_API_KEY=test-api-key-change-in-production
      - WORKDIR=/tmp/bytebot-workdir
      - MAX_FILE_SIZE_MB=10
      - REQUEST_TIMEOUT=30
      - RETRY_ATTEMPTS=3
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8080
    volumes:
      - ./config:/app/config:ro
      - ./workdir:/tmp/bytebot-workdir
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8089/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
