name: Gateway CI

on:
  push:
    paths:
      - '00-pipelines-gateway/**'
  pull_request:
    paths:
      - '00-pipelines-gateway/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 00-pipelines-gateway
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        env:
          PYTHONPATH: src
        run: pytest -q
